add retrofit
fatimaNoori77/LearningAndroid pull request #4
Opened 2024-10-01 09:30 UTC by fatimaNoori77

I have added the Retrofit library to this branch.

2024-10-01 13:35 UTC, Kaaveh requested changes

2024-10-01 13:35 UTC, Kaaveh commented on app/src/main/java/ir/noori/learningandroid/RetrofitInstance.kt
> +        .baseUrl("https://jsonplaceholder.typicode.com/")
Create a `const` for the base URL.

2024-10-01 13:37 UTC, Kaaveh commented
When you open a PR, please mention the issue for closing it automatically. For example: fix #3

2024-10-02 06:49 UTC, fatimaNoori77 commented on app/src/main/java/ir/noori/learningandroid/RetrofitInstance.kt
> +        .baseUrl("https://jsonplaceholder.typicode.com/")
Done

2024-10-02 10:09 UTC, Kaaveh approved these changes

2024-10-05 09:41 UTC, merged